export const states = [
  {
    stateName: "Alabama",
    conservative: 9,
    beauty: 36,
    cost: 2,
    costal: true,
    averageTemp: 62.8,
    propertyAppreciation: 4.42,
    propertyTaxes: 2,
    populationPerSquareMile: 100.65,
    crimeRate: 22,
    education: 44,
  },
  {
    stateName: "Alaska",
    conservative: 19,
    beauty: 3,
    cost: 40,
    costal: true,
    averageTemp: 26.6,
    propertyAppreciation: 5.75,
    propertyTaxes: 30,
    populationPerSquareMile: 1.3,
    crimeRate: 10,
    education: 49,
  },
  {
    stateName: "Arizona",
    conservative: 27,
    beauty: 9,
    cost: 32,
    costal: false,
    averageTemp: 60.3,
    propertyAppreciation: 6.63,
    propertyTaxes: 11,
    populationPerSquareMile: 64.96,
    crimeRate: 13,
    education: 45,
  },
  {
    stateName: "Arkansas",
    conservative: 6,
    beauty: 27,
    cost: 3,
    costal: false,
    averageTemp: 60.4,
    propertyAppreciation: 5.86,
    propertyTaxes: 12,
    populationPerSquareMile: 58.43,
    crimeRate: 2,
    education: 43,
  },
  {
    stateName: "California",
    conservative: 45,
    beauty: 1,
    cost: 50,
    costal: true,
    averageTemp: 59.4,
    propertyAppreciation: 4.91,
    propertyTaxes: 18,
    populationPerSquareMile: 258.21,
    crimeRate: 5,
    education: 20,
  },
  {
    stateName: "Colorado",
    conservative: 36,
    beauty: 5,
    cost: 43,
    costal: false,
    averageTemp: 45.1,
    propertyAppreciation: 3.31,
    propertyTaxes: 3,
    populationPerSquareMile: 57.86,
    crimeRate: 4,
    education: 4,
  },
  {
    stateName: "Connecticut",
    conservative: 40,
    beauty: 40,
    cost: 42,
    costal: true,
    averageTemp: 49,
    propertyAppreciation: 12.19,
    propertyTaxes: 46,
    populationPerSquareMile: 746.7,
    crimeRate: 47,
    education: 8,
  },
  {
    stateName: "Delaware",
    conservative: 41,
    beauty: 39,
    cost: 30,
    costal: true,
    averageTemp: 55.3,
    propertyAppreciation: 4.73,
    propertyTaxes: 10,
    populationPerSquareMile: 522.09,
    crimeRate: 21,
    education: 30,
  },
  {
    stateName: "Florida",
    conservative: 24,
    beauty: 18,
    cost: 38,
    costal: true,
    averageTemp: 70.7,
    propertyAppreciation: 6.85,
    propertyTaxes: 25,
    populationPerSquareMile: 416.96,
    crimeRate: 39,
    education: 1,
  },
  {
    stateName: "Georgia",
    conservative: 25,
    beauty: 33,
    cost: 25,
    costal: true,
    averageTemp: 63.5,
    propertyAppreciation: 7.16,
    propertyTaxes: 26,
    populationPerSquareMile: 191.59,
    crimeRate: 26,
    education: 27,
  },
  {
    stateName: "Hawaii",
    conservative: 34,
    beauty: 2,
    cost: 49,
    costal: true,
    averageTemp: 70,
    propertyAppreciation: -3.44,
    propertyTaxes: 1,
    populationPerSquareMile: 231.01,
    crimeRate: 25,
    education: 24,
  },
  {
    stateName: "Idaho",
    conservative: 5,
    beauty: 16,
    cost: 22,
    costal: false,
    averageTemp: 44.5,
    propertyAppreciation: 0.54,
    propertyTaxes: 13,
    populationPerSquareMile: 23.24,
    crimeRate: 45,
    education: 22,
  },
  {
    stateName: "Illinois",
    conservative: 42,
    beauty: 48,
    cost: 35,
    costal: false,
    averageTemp: 51.8,
    propertyAppreciation: 8.37,
    propertyTaxes: 49,
    populationPerSquareMile: 230.68,
    crimeRate: 32,
    education: 12,
  },
  {
    stateName: "Indiana",
    conservative: 14,
    beauty: 47,
    cost: 15,
    costal: false,
    averageTemp: 51.7,
    propertyAppreciation: 8.02,
    propertyTaxes: 21,
    populationPerSquareMile: 191.93,
    crimeRate: 31,
    education: 17,
  },
  {
    stateName: "Iowa",
    conservative: 21,
    beauty: 50,
    cost: 6,
    costal: false,
    averageTemp: 47.8,
    propertyAppreciation: 5.58,
    propertyTaxes: 41,
    populationPerSquareMile: 57.89,
    crimeRate: 37,
    education: 13,
  },
  {
    stateName: "Kansas",
    conservative: 17,
    beauty: 49,
    cost: 11,
    costal: false,
    averageTemp: 54.3,
    propertyAppreciation: 8.82,
    propertyTaxes: 36,
    populationPerSquareMile: 36.24,
    crimeRate: 15,
    education: 26,
  },
  {
    stateName: "Kentucky",
    conservative: 7,
    beauty: 31,
    cost: 4,
    costal: false,
    averageTemp: 55.6,
    propertyAppreciation: 6.42,
    propertyTaxes: 20,
    populationPerSquareMile: 115.38,
    crimeRate: 44,
    education: 32,
  },
  {
    stateName: "Louisiana",
    conservative: 13,
    beauty: 38,
    cost: 9,
    costal: true,
    averageTemp: 66.4,
    propertyAppreciation: 2.12,
    propertyTaxes: 5,
    populationPerSquareMile: 108.67,
    crimeRate: 3,
    education: 46,
  },
  {
    stateName: "Maine",
    conservative: 48,
    beauty: 15,
    cost: 26,
    costal: true,
    averageTemp: 41,
    propertyAppreciation: 7.42,
    propertyTaxes: 35,
    populationPerSquareMile: 44.5,
    crimeRate: 49,
    education: 34,
  },
  {
    stateName: "Maryland",
    conservative: 35,
    beauty: 29,
    cost: 44,
    costal: true,
    averageTemp: 54.2,
    propertyAppreciation: 5.86,
    propertyTaxes: 31,
    populationPerSquareMile: 648.84,
    crimeRate: 24,
    education: 23,
  },
  {
    stateName: "Massachusetts",
    conservative: 33,
    beauty: 28,
    cost: 45,
    costal: true,
    averageTemp: 47.9,
    propertyAppreciation: 9.12,
    propertyTaxes: 33,
    populationPerSquareMile: 919.82,
    crimeRate: 35,
    education: 3,
  },
  {
    stateName: "Michigan",
    conservative: 30,
    beauty: 8,
    cost: 24,
    costal: false,
    averageTemp: 44.4,
    propertyAppreciation: 9.65,
    propertyTaxes: 37,
    populationPerSquareMile: 179.26,
    crimeRate: 20,
    education: 37,
  },
  {
    stateName: "Minnesota",
    conservative: 49,
    beauty: 24,
    cost: 29,
    costal: false,
    averageTemp: 41.2,
    propertyAppreciation: 4.09,
    propertyTaxes: 32,
    populationPerSquareMile: 73.18,
    crimeRate: 28,
    education: 21,
  },
  {
    stateName: "Mississippi",
    conservative: 15,
    beauty: 45,
    cost: 1,
    costal: true,
    averageTemp: 63.4,
    propertyAppreciation: 9.69,
    propertyTaxes: 15,
    populationPerSquareMile: 63.07,
    crimeRate: 36,
    education: 41,
  },
  {
    stateName: "Missouri",
    conservative: 18,
    beauty: 41,
    cost: 13,
    costal: false,
    averageTemp: 54.5,
    propertyAppreciation: 7.99,
    propertyTaxes: 29,
    populationPerSquareMile: 90.26,
    crimeRate: 7,
    education: 31,
  },
  {
    stateName: "Montana",
    conservative: 16,
    beauty: 11,
    cost: 19,
    costal: false,
    averageTemp: 42.7,
    propertyAppreciation: 3.75,
    propertyTaxes: 17,
    populationPerSquareMile: 7.64,
    crimeRate: 17,
    education: 25,
  },
  {
    stateName: "Nebraska",
    conservative: 11,
    beauty: 43,
    cost: 17,
    costal: false,
    averageTemp: 48.8,
    propertyAppreciation: 4.86,
    propertyTaxes: 44,
    populationPerSquareMile: 26.06,
    crimeRate: 30,
    education: 7,
  },
  {
    stateName: "Nevada",
    conservative: 31,
    beauty: 26,
    cost: 34,
    costal: false,
    averageTemp: 49.9,
    propertyAppreciation: 3.39,
    propertyTaxes: 9,
    populationPerSquareMile: 29.38,
    crimeRate: 9,
    education: 38,
  },
  {
    stateName: "New Hampshire",
    conservative: 50,
    beauty: 32,
    cost: 36,
    costal: true,
    averageTemp: 43.8,
    propertyAppreciation: 9.16,
    propertyTaxes: 48,
    populationPerSquareMile: 155.91,
    crimeRate: 50,
    education: 19,
  },
  {
    stateName: "New Jersey",
    conservative: 43,
    beauty: 37,
    cost: 48,
    costal: true,
    averageTemp: 52.7,
    propertyAppreciation: 11.38,
    propertyTaxes: 50,
    populationPerSquareMile: 1283.4,
    crimeRate: 46,
    education: 2,
  },
  {
    stateName: "New Mexico",
    conservative: 46,
    beauty: 14,
    cost: 10,
    costal: false,
    averageTemp: 53.4,
    propertyAppreciation: 5.05,
    propertyTaxes: 16,
    populationPerSquareMile: 17.6,
    crimeRate: 1,
    education: 50,
  },
  {
    stateName: "New York",
    conservative: 37,
    beauty: 17,
    cost: 47,
    costal: true,
    averageTemp: 45.4,
    propertyAppreciation: 9.62,
    propertyTaxes: 39,
    populationPerSquareMile: 433.9,
    crimeRate: 19,
    education: 9,
  },
  {
    stateName: "North Carolina",
    conservative: 26,
    beauty: 12,
    cost: 23,
    costal: true,
    averageTemp: 59,
    propertyAppreciation: 6.98,
    propertyTaxes: 28,
    populationPerSquareMile: 220.3,
    crimeRate: 16,
    education: 16,
  },
  {
    stateName: "North Dakota",
    conservative: 3,
    beauty: 42,
    cost: 12,
    costal: false,
    averageTemp: 40.4,
    propertyAppreciation: 4.88,
    propertyTaxes: 0,
    populationPerSquareMile: 11.75,
    crimeRate: 29,
    education: 28,
  },
  {
    stateName: "Ohio",
    conservative: 22,
    beauty: 44,
    cost: 16,
    costal: false,
    averageTemp: 50.7,
    propertyAppreciation: 9.23,
    propertyTaxes: 42,
    populationPerSquareMile: 290.7,
    crimeRate: 27,
    education: 29,
  },
  {
    stateName: "Oklahoma",
    conservative: 4,
    beauty: 46,
    cost: 7,
    costal: false,
    averageTemp: 59.6,
    propertyAppreciation: 5.14,
    propertyTaxes: 24,
    populationPerSquareMile: 58.63,
    crimeRate: 12,
    education: 48,
  },
  {
    stateName: "Oregon",
    conservative: 44,
    beauty: 7,
    cost: 41,
    costal: true,
    averageTemp: 48.4,
    propertyAppreciation: 1.62,
    propertyTaxes: 27,
    populationPerSquareMile: 45.41,
    crimeRate: 18,
    education: 39,
  },
  {
    stateName: "Pennsylvania",
    conservative: 28,
    beauty: 35,
    cost: 27,
    costal: false,
    averageTemp: 48.8,
    propertyAppreciation: 6.88,
    propertyTaxes: 40,
    populationPerSquareMile: 292.62,
    crimeRate: 38,
    education: 36,
  },
  {
    stateName: "Rhode Island",
    conservative: 38,
    beauty: 34,
    cost: 37,
    costal: true,
    averageTemp: 50.1,
    propertyAppreciation: 15.11,
    propertyTaxes: 38,
    populationPerSquareMile: 1074.3,
    crimeRate: 48,
    education: 40,
  },
  {
    stateName: "South Carolina",
    conservative: 20,
    beauty: 30,
    cost: 21,
    costal: true,
    averageTemp: 62.4,
    propertyAppreciation: 9.42,
    propertyTaxes: 6,
    populationPerSquareMile: 175.19,
    crimeRate: 8,
    education: 42,
  },
  {
    stateName: "South Dakota",
    conservative: 8,
    beauty: 21,
    cost: 8,
    costal: false,
    averageTemp: 45.2,
    propertyAppreciation: 6.79,
    propertyTaxes: 34,
    populationPerSquareMile: 11.98,
    crimeRate: 23,
    education: 18,
  },
  {
    stateName: "Tennessee",
    conservative: 10,
    beauty: 20,
    cost: 14,
    costal: false,
    averageTemp: 57.6,
    propertyAppreciation: 6.24,
    propertyTaxes: 14,
    populationPerSquareMile: 171.71,
    crimeRate: 6,
    education: 33,
  },
  {
    stateName: "Texas",
    conservative: 23,
    beauty: 22,
    cost: 33,
    costal: true,
    averageTemp: 64.8,
    propertyAppreciation: 2.73,
    propertyTaxes: 45,
    populationPerSquareMile: 116.16,
    crimeRate: 11,
    education: 35,
  },
  {
    stateName: "Utah",
    conservative: 12,
    beauty: 4,
    cost: 28,
    costal: false,
    averageTemp: 48.6,
    propertyAppreciation: 2,
    propertyTaxes: 8,
    populationPerSquareMile: 41.67,
    crimeRate: 34,
    education: 5,
  },
  {
    stateName: "Vermont",
    conservative: 32,
    beauty: 13,
    cost: 31,
    costal: false,
    averageTemp: 42.9,
    propertyAppreciation: 13.26,
    propertyTaxes: 47,
    populationPerSquareMile: 73.34,
    crimeRate: 41,
    education: 15,
  },
  {
    stateName: "Virginia",
    conservative: 47,
    beauty: 25,
    cost: 39,
    costal: true,
    averageTemp: 55.1,
    propertyAppreciation: 7.32,
    propertyTaxes: 23,
    populationPerSquareMile: 223.36,
    crimeRate: 40,
    education: 11,
  },
  {
    stateName: "Washington",
    conservative: 39,
    beauty: 6,
    cost: 46,
    costal: true,
    averageTemp: 48.3,
    propertyAppreciation: 3.19,
    propertyTaxes: 22,
    populationPerSquareMile: 120.37,
    crimeRate: 14,
    education: 10,
  },
  {
    stateName: "West Virginia",
    conservative: 2,
    beauty: 19,
    cost: 5,
    costal: false,
    averageTemp: 51.8,
    propertyAppreciation: 12.39,
    propertyTaxes: 7,
    populationPerSquareMile: 73.88,
    crimeRate: 42,
    education: 47,
  },
  {
    stateName: "Wisconsin",
    conservative: 29,
    beauty: 23,
    cost: 20,
    costal: false,
    averageTemp: 43.1,
    propertyAppreciation: 9.28,
    propertyTaxes: 43,
    populationPerSquareMile: 109.97,
    crimeRate: 33,
    education: 6,
  },
  {
    stateName: "Wyoming",
    conservative: 1,
    beauty: 10,
    cost: 18,
    costal: false,
    averageTemp: 42,
    propertyAppreciation: 3.69,
    propertyTaxes: 4,
    populationPerSquareMile: 5.98,
    crimeRate: 43,
    education: 14,
  },
] as const;
