export const states = [
  {
    stateName: "Alabama",
    conservative: 9,
    beauty: 36,
    cost: 2,
    costal: true,
    averageTemp: 62.8,
  },
  {
    stateName: "Alaska",
    conservative: 19,
    beauty: 3,
    cost: 40,
    costal: true,
    averageTemp: 26.6,
  },
  {
    stateName: "Arizona",
    conservative: 27,
    beauty: 9,
    cost: 32,
    costal: false,
    averageTemp: 60.3,
  },
  {
    stateName: "Arkansas",
    conservative: 6,
    beauty: 27,
    cost: 3,
    costal: false,
    averageTemp: 60.4,
  },
  {
    stateName: "California",
    conservative: 45,
    beauty: 1,
    cost: 50,
    costal: true,
    averageTemp: 59.4,
  },
  {
    stateName: "Colorado",
    conservative: 36,
    beauty: 5,
    cost: 43,
    costal: false,
    averageTemp: 45.1,
  },
  {
    stateName: "Connecticut",
    conservative: 40,
    beauty: 40,
    cost: 42,
    costal: true,
    averageTemp: 49,
  },
  {
    stateName: "Delaware",
    conservative: 41,
    beauty: 39,
    cost: 30,
    costal: true,
    averageTemp: 55.3,
  },
  {
    stateName: "Florida",
    conservative: 24,
    beauty: 18,
    cost: 38,
    costal: true,
    averageTemp: 70.7,
  },
  {
    stateName: "Georgia",
    conservative: 25,
    beauty: 33,
    cost: 25,
    costal: true,
    averageTemp: 63.5,
  },
  {
    stateName: "Hawaii",
    conservative: 34,
    beauty: 2,
    cost: 49,
    costal: true,
    averageTemp: 70,
  },
  {
    stateName: "Idaho",
    conservative: 5,
    beauty: 16,
    cost: 22,
    costal: false,
    averageTemp: 44.5,
  },
  {
    stateName: "Illinois",
    conservative: 42,
    beauty: 48,
    cost: 35,
    costal: false,
    averageTemp: 51.8,
  },
  {
    stateName: "Indiana",
    conservative: 14,
    beauty: 47,
    cost: 15,
    costal: false,
    averageTemp: 51.7,
  },
  {
    stateName: "Iowa",
    conservative: 21,
    beauty: 50,
    cost: 6,
    costal: false,
    averageTemp: 47.8,
  },
  {
    stateName: "Kansas",
    conservative: 17,
    beauty: 49,
    cost: 11,
    costal: false,
    averageTemp: 54.3,
  },
  {
    stateName: "Kentucky",
    conservative: 7,
    beauty: 31,
    cost: 4,
    costal: false,
    averageTemp: 55.6,
  },
  {
    stateName: "Louisiana",
    conservative: 13,
    beauty: 38,
    cost: 9,
    costal: true,
    averageTemp: 66.4,
  },
  {
    stateName: "Maine",
    conservative: 48,
    beauty: 15,
    cost: 26,
    costal: true,
    averageTemp: 41,
  },
  {
    stateName: "Maryland",
    conservative: 35,
    beauty: 29,
    cost: 44,
    costal: true,
    averageTemp: 54.2,
  },
  {
    stateName: "Massachusetts",
    conservative: 33,
    beauty: 28,
    cost: 45,
    costal: true,
    averageTemp: 47.9,
  },
  {
    stateName: "Michigan",
    conservative: 30,
    beauty: 8,
    cost: 24,
    costal: false,
    averageTemp: 44.4,
  },
  {
    stateName: "Minnesota",
    conservative: 49,
    beauty: 24,
    cost: 29,
    costal: false,
    averageTemp: 41.2,
  },
  {
    stateName: "Mississippi",
    conservative: 15,
    beauty: 45,
    cost: 1,
    costal: true,
    averageTemp: 63.4,
  },
  {
    stateName: "Missouri",
    conservative: 18,
    beauty: 41,
    cost: 13,
    costal: false,
    averageTemp: 54.5,
  },
  {
    stateName: "Montana",
    conservative: 16,
    beauty: 11,
    cost: 19,
    costal: false,
    averageTemp: 42.7,
  },
  {
    stateName: "Nebraska",
    conservative: 11,
    beauty: 43,
    cost: 17,
    costal: false,
    averageTemp: 48.8,
  },
  {
    stateName: "Nevada",
    conservative: 31,
    beauty: 26,
    cost: 34,
    costal: false,
    averageTemp: 49.9,
  },
  {
    stateName: "New Hampshire",
    conservative: 50,
    beauty: 32,
    cost: 36,
    costal: true,
    averageTemp: 43.8,
  },
  {
    stateName: "New Jersey",
    conservative: 43,
    beauty: 37,
    cost: 48,
    costal: true,
    averageTemp: 52.7,
  },
  {
    stateName: "New Mexico",
    conservative: 46,
    beauty: 14,
    cost: 10,
    costal: false,
    averageTemp: 53.4,
  },
  {
    stateName: "New York",
    conservative: 37,
    beauty: 17,
    cost: 47,
    costal: true,
    averageTemp: 45.4,
  },
  {
    stateName: "North Carolina",
    conservative: 26,
    beauty: 12,
    cost: 23,
    costal: true,
    averageTemp: 59,
  },
  {
    stateName: "North Dakota",
    conservative: 3,
    beauty: 42,
    cost: 12,
    costal: false,
    averageTemp: 40.4,
  },
  {
    stateName: "Ohio",
    conservative: 22,
    beauty: 44,
    cost: 16,
    costal: false,
    averageTemp: 50.7,
  },
  {
    stateName: "Oklahoma",
    conservative: 4,
    beauty: 46,
    cost: 7,
    costal: false,
    averageTemp: 59.6,
  },
  {
    stateName: "Oregon",
    conservative: 44,
    beauty: 7,
    cost: 41,
    costal: true,
    averageTemp: 48.4,
  },
  {
    stateName: "Pennsylvania",
    conservative: 28,
    beauty: 35,
    cost: 27,
    costal: false,
    averageTemp: 48.8,
  },
  {
    stateName: "Rhode Island",
    conservative: 38,
    beauty: 34,
    cost: 37,
    costal: true,
    averageTemp: 50.1,
  },
  {
    stateName: "South Carolina",
    conservative: 20,
    beauty: 30,
    cost: 21,
    costal: true,
    averageTemp: 62.4,
  },
  {
    stateName: "South Dakota",
    conservative: 8,
    beauty: 21,
    cost: 8,
    costal: false,
    averageTemp: 45.2,
  },
  {
    stateName: "Tennessee",
    conservative: 10,
    beauty: 20,
    cost: 14,
    costal: false,
    averageTemp: 57.6,
  },
  {
    stateName: "Texas",
    conservative: 23,
    beauty: 22,
    cost: 33,
    costal: true,
    averageTemp: 64.8,
  },
  {
    stateName: "Utah",
    conservative: 12,
    beauty: 4,
    cost: 28,
    costal: false,
    averageTemp: 48.6,
  },
  {
    stateName: "Vermont",
    conservative: 32,
    beauty: 13,
    cost: 31,
    costal: false,
    averageTemp: 42.9,
  },
  {
    stateName: "Virginia",
    conservative: 47,
    beauty: 25,
    cost: 39,
    costal: true,
    averageTemp: 55.1,
  },
  {
    stateName: "Washington",
    conservative: 39,
    beauty: 6,
    cost: 46,
    costal: true,
    averageTemp: 48.3,
  },
  {
    stateName: "West Virginia",
    conservative: 2,
    beauty: 19,
    cost: 5,
    costal: false,
    averageTemp: 51.8,
  },
  {
    stateName: "Wisconsin",
    conservative: 29,
    beauty: 23,
    cost: 20,
    costal: false,
    averageTemp: 43.1,
  },
  {
    stateName: "Wyoming",
    conservative: 1,
    beauty: 10,
    cost: 18,
    costal: false,
    averageTemp: 42,
  },
] as const;
